### student

GET http://localhost:3000/student/10A
###
POST http://localhost:3000/student/register
Content-Type: application/json

{
  "name": "John Doe",
  "classes": "BBA",
  "email": "anmol@gmail.com",
  "enroll_no": "CBD133",
  "password": "mypassword"
}
###
GET http://localhost:3000/student/timetable
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWRhZmZmMTljNDIxMjY2N2Y0YmE0YSIsImlhdCI6MTY3OTY2NzE5OX0.B4OgIbVeqZonrvAB1DH6Hup0jiXHt5we41eIIRIvWrY
###
POST  http://localhost:3000/student/signin
Content-Type: application/json

{ 
  "enroll_no":"CBD1233",
  "password" : "mypassword"
}
###